version: "3.7"

services:
  sensor-dashboard-frontend:
    container_name: sensor-dashboard-frontend
    build:
      context: .
    ports:
      - ${SERVER_PORT}:80
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
